### ISSUE TITLE
Why there are max_epoch and max_iter?

### ISSUE THREAD

**Issue by EDDChang** [shachoi/RobustNet#17]
As title, why you use max_iter in training loop but still have max_epoch in args?

**Comment by fingerk28** [comment]
Hi,
I have the same question. In the default setting, the max_iter=40000, which is mean that the network just need to be trained 38 epoch? (number of images is 12388 in GTA, equal to 1032 batch (batch size=12), 40000/1032 = 38.75)
Thank you!

**Comment by shachoi** [comment]
Hi,
As you know, the optimal epoch can be different depending on your batch size, network architecture, datasets, and so on.
Therefore, training on GTAV may require more iterations as the number of GTAV images is much higher than for Cityscapes.
But, I simply conducted the entire experiment with a fixed iteration of 40K.
Our study does not need to find the optimal epoch, compares our method with other methods under the fair conditions.

It is required to find optimal values ​​for various parameters in order to compete with other methods for best performance in the leaderboard, but our study has not covered this competition.

Thank you!
Sungha.

**Comment by fingerk28** [comment]
I got it. Thanks for your help. : )
