### ISSUE TITLE
Low results for RobustNet with ResNet-101 backbone

### ISSUE THREAD

**Issue by Making24** [shachoi/RobustNet#9]
Hi, I tried the experiment with ResNet-101 for ISW by training on the GTAV (I changed the script based on the city_isw_r101.sh). However, I got results that are similar to ResNet-50. For example, the mIoU in Cityscape is 36%. 

Do you have any results on ResNet-101 for GTAV? And how to train ISW with ResNet-101 for GTAV?

**Comment by Trainingzy** [comment]
Hi @shachoi, thank you for your code and great work.

I am curious about the performance of ResNet101 backbone, widely used in other works. I cannot get satisfactory performance with the same training strategy as [ResNet50](https://github.com/shachoi/RobustNet/blob/56cb41baa286082dfa7f534ea56750bc091e1842/scripts/train_r50os16_gtav_isw.sh). The performance is much lower than other DG methods.

**Comment by shachoi** [comment]
@Making24 @Trainingzy
Sorry for the delayed response and thank you for your interest in our work.
Unfortunately, we haven't tested ResNet-101 on the GTA dataset. I'll try it out and let you know.
@Trainingzy 
Are you asking about the results of training with GTAV?

**Comment by Trainingzy** [comment]
Thank you for your reply.

Yes, I am asking about the results of GTAV --> CityScapes DG setting.

**Comment by shachoi** [comment]
@Trainingzy @Making24 
Sorry for the wait.

We adopted ResNet-101 which has three 3x3 convolutions in the first layer.
In the original script, whitening was applied to the last convolution among the three convolutions in the first layer.
> --wt_layer 0 0 2 2 2 0 0 \

But this seems wrong. Performance is higher when whitening is applied to the preceding two convolutions.
> --wt_layer 2 2 0 2 2 0 0 \

The averages of the three experimental results for each model are as follows.
|Model|BDD|Cityscapes|Mapillary|Synthia|GTAV|
|------|---|---|---|---|---|
|Baseline|24.85|30.06|31.50|28.78|74.71|
|IBN|33.30|33.63|36.50|31.32|74.46|
|ISW|35.37|37.09|38.50|30.49|74.49|

I updated the script, please let me know if you need pre-trained models.
I think the reason the performance is lower than the methods in other papers is because several factors such as hyperparameters used in training and inference techniques can affect performance.

**Comment by Making24** [comment]
@shachoi Thanks for your reply and results. I will try it. More questions.

1. Did you apply this layer modification for IBN? Could you provide BASE, IBN and ISW scripts for R101 of GTAV? I did not find it now.
2. Could you provide the training scripts and results of SYNTHIA (single domain)?

**Comment by shachoi** [comment]
@Making24
Sorry. I haven't tried training on Synthia.
